# A workflow to build and push a Docker image to Docker Hub
name: Build and Push Docker Image

# Run this workflow on pushes to the 'main' branch and manually
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Define the jobs to be executed
jobs:
  build:
    # Use the latest version of Ubuntu as the runner environment
    runs-on: ubuntu-latest

    # Define the steps for the job
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dmr138/greatstack-weather:latest
          build-args:VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
